apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-webservice
  namespace: rasax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa-webservice
  template:
    metadata:
      labels:
        app: rasa-webservice
    spec:
      containers:
        - name: rasa-webservice
          image: joes4/chatbot-webservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rasa-webservice-ingress
  namespace: rasax
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: lets-encrypt
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "ALLOW-FROM https://joel-schlotthauer.com";
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - Please provide valid credentials'
spec:
spec:
  tls:
  - hosts:
    - joel-schlotthauer.com
    secretName: rasa-webservice-ingress-tls
  rules:
  - host: joel-schlotthauer.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rasa-webservice-service
            port:
              name: http