apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa-webservice
  namespace: rasax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa-webservice
  template:
    metadata:
      labels:
        app: rasa-webservice
    spec:
      containers:
        - name: rasa-webservice
          image: joes4/chatbot-webservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80